### ISSUE TITLE
Feat: 스택오버플로 홈 디자인 클론

### ISSUE THREAD

**Issue by devfrank9** [SEB39-Team/SEB39_Pre_Front#1]
## 개요

스택오버플로 홈페이지 보고 똑같이 클로닝 디자인 만들기

## 소요시간

~ASAP

## TODO

- [ ] 
- [ ] 
- [ ]

**Comment by Kyoorim** [comment]
종호님 글을 제가 잘못 편집한것 같네요 ㅜㅜㅋㅋ
